import type { PlatformAnalysis } from '@/types/pipeline';

// TODO: API 연동 후 제거
export const MOCK_ANALYSIS_RESULTS: PlatformAnalysis[] = [
  {
    platformId: 'news',
    platformLabel: '뉴스',
    category: '뉴스',
    sirScore: 78,
    positive: 72,
    neutral: 18,
    negative: 10,
    articles: [
      { title: '삼성전자, 2분기 영업이익 시장 기대치 상회', url: 'https://news.naver.com/article/001', sentiment: 'positive' },
      { title: '삼성전자 반도체 부문 회복세 뚜렷…HBM 수주 확대', url: 'https://news.naver.com/article/002', sentiment: 'positive' },
      { title: '삼성전자, 갤럭시 신제품 출시 앞두고 기대감 상승', url: 'https://news.naver.com/article/003', sentiment: 'positive' },
      { title: '삼성전자 주가 52주 신고가 경신…외국인 매수세', url: 'https://news.naver.com/article/004', sentiment: 'positive' },
      { title: '"삼성전자 목표가 상향" 증권사 리포트 잇따라', url: 'https://news.naver.com/article/005', sentiment: 'neutral' },
      { title: '삼성전자 리콜 이슈, 소비자 불만 확산 중', url: 'https://news.naver.com/article/006', sentiment: 'negative' },
    ],
    flagged: [
      {
        title: '삼성전자 리콜 이슈, 소비자 불만 확산 중',
        url: 'https://news.naver.com/article/006',
        sentiment: 'negative',
        reason: '리콜 관련 부정 여론',
      },
    ],
  },
  {
    platformId: 'naver-stock-forum',
    platformLabel: '네이버증권 종목토론방',
    category: '커뮤니티',
    sirScore: 58,
    positive: 45,
    neutral: 25,
    negative: 30,
    articles: [
      { title: '삼성전자 이번 실적 진짜 좋네요', url: 'https://finance.naver.com/item/board_read.nhn?code=005930&nid=1', sentiment: 'positive' },
      { title: 'HBM 관련 수혜 기대합니다', url: 'https://finance.naver.com/item/board_read.nhn?code=005930&nid=2', sentiment: 'positive' },
      { title: '외국인 매수세 지속 중 의견 공유', url: 'https://finance.naver.com/item/board_read.nhn?code=005930&nid=3', sentiment: 'neutral' },
      { title: '삼전 경영진 무능하다 진짜', url: 'https://finance.naver.com/item/board_read.nhn?code=005930&nid=10', sentiment: 'negative' },
      { title: '삼성 반도체 TSMC한테 밀리는 거 아님?', url: 'https://finance.naver.com/item/board_read.nhn?code=005930&nid=11', sentiment: 'negative' },
    ],
    flagged: [
      {
        title: '삼전 경영진 무능하다 진짜',
        url: 'https://finance.naver.com/item/board_read.nhn?code=005930&nid=10',
        sentiment: 'negative',
        reason: '경영진 비판 여론',
      },
      {
        title: '삼성 반도체 TSMC한테 밀리는 거 아님?',
        url: 'https://finance.naver.com/item/board_read.nhn?code=005930&nid=11',
        sentiment: 'caution',
        reason: '경쟁사 비교 부정 프레이밍',
      },
    ],
  },
  {
    platformId: 'paxnet',
    platformLabel: '팍스넷',
    category: '커뮤니티',
    sirScore: 65,
    positive: 50,
    neutral: 30,
    negative: 20,
    articles: [
      { title: '삼성전자 반도체 사이클 바닥 확인?', url: 'https://paxnet.co.kr/stock/report/1', sentiment: 'positive' },
      { title: '삼전 차트 분석 — 돌파 시그널 감지', url: 'https://paxnet.co.kr/stock/report/2', sentiment: 'neutral' },
    ],
    flagged: [],
  },
  {
    platformId: 'dcinside-stock',
    platformLabel: '디시인사이드 주식갤러리',
    category: '커뮤니티',
    sirScore: 42,
    positive: 30,
    neutral: 25,
    negative: 45,
    articles: [
      { title: '삼성전자 실적 발표 요약 정리', url: 'https://gall.dcinside.com/board/view/?id=stock&no=1', sentiment: 'neutral' },
      { title: '삼전 8만전자 가나요?', url: 'https://gall.dcinside.com/board/view/?id=stock&no=2', sentiment: 'positive' },
      { title: '삼성 망한다 ㅋㅋ 탈출각', url: 'https://gall.dcinside.com/board/view/?id=stock&no=5', sentiment: 'negative' },
      { title: '삼성 파운드리 수율 문제 심각하다는 소문', url: 'https://gall.dcinside.com/board/view/?id=stock&no=6', sentiment: 'negative' },
    ],
    flagged: [
      {
        title: '삼성 망한다 ㅋㅋ 탈출각',
        url: 'https://gall.dcinside.com/board/view/?id=stock&no=5',
        sentiment: 'negative',
        reason: '극단적 부정 여론',
      },
      {
        title: '삼성 파운드리 수율 문제 심각하다는 소문',
        url: 'https://gall.dcinside.com/board/view/?id=stock&no=6',
        sentiment: 'caution',
        reason: '미확인 루머 확산',
      },
    ],
  },
  {
    platformId: 'ppomppu-stock',
    platformLabel: '뽐뿌 주식포럼',
    category: '커뮤니티',
    sirScore: 70,
    positive: 55,
    neutral: 30,
    negative: 15,
    articles: [
      { title: '삼성전자 장기 보유 후기', url: 'https://ppomppu.co.kr/zboard/view.php?id=stock&no=1', sentiment: 'positive' },
      { title: '삼전 배당금 정리 (2026년 기준)', url: 'https://ppomppu.co.kr/zboard/view.php?id=stock&no=2', sentiment: 'neutral' },
    ],
    flagged: [],
  },
  {
    platformId: 'naver',
    platformLabel: '네이버',
    category: '포털',
    sirScore: 74,
    positive: 62,
    neutral: 23,
    negative: 15,
    articles: [
      { title: '삼성전자 실적 분석 — 2026년 상반기 전망', url: 'https://search.naver.com/search.nhn?query=samsung+1', sentiment: 'positive' },
      { title: '삼성전자 주가 전망 총정리', url: 'https://search.naver.com/search.nhn?query=samsung+2', sentiment: 'neutral' },
      { title: '삼성전자 품질 이슈 연이어 발생…소비자 신뢰 하락', url: 'https://search.naver.com/search.nhn?query=samsung+quality', sentiment: 'negative' },
    ],
    flagged: [
      {
        title: '삼성전자 품질 이슈 연이어 발생…소비자 신뢰 하락',
        url: 'https://search.naver.com/search.nhn?query=samsung+quality',
        sentiment: 'caution',
        reason: '품질 관련 부정 검색 트렌드 상승',
      },
    ],
  },
  {
    platformId: 'youtube',
    platformLabel: '유튜브',
    category: 'SNS',
    sirScore: 68,
    positive: 55,
    neutral: 25,
    negative: 20,
    articles: [
      { title: '[긴급] 삼성전자 실적 발표 리뷰 — 반도체 슈퍼사이클 시작?', url: 'https://youtube.com/watch?v=abc1', sentiment: 'positive' },
      { title: '삼성전자 주가 전망 2026 하반기 분석', url: 'https://youtube.com/watch?v=abc2', sentiment: 'neutral' },
      { title: '삼성 vs TSMC HBM 경쟁 구도 정리', url: 'https://youtube.com/watch?v=abc3', sentiment: 'neutral' },
      { title: '[폭로] 삼성전자 내부 사정 다 알려드림', url: 'https://youtube.com/watch?v=flag1', sentiment: 'negative' },
    ],
    flagged: [
      {
        title: '[폭로] 삼성전자 내부 사정 다 알려드림',
        url: 'https://youtube.com/watch?v=flag1',
        sentiment: 'caution',
        reason: '자극적 제목 — 조회수 10만 이상',
      },
    ],
  },
  {
    platformId: 'instagram',
    platformLabel: '인스타그램',
    category: 'SNS',
    sirScore: 75,
    positive: 65,
    neutral: 25,
    negative: 10,
    articles: [
      { title: '#삼성전자 #투자 — 실적 호조 반응 모음', url: 'https://instagram.com/p/samsung1', sentiment: 'positive' },
      { title: '#갤럭시S26 #삼성 — 신제품 기대 포스트', url: 'https://instagram.com/p/samsung2', sentiment: 'positive' },
    ],
    flagged: [],
  },
  {
    platformId: 'naver-cafe',
    platformLabel: '네이버 카페',
    category: 'SNS',
    sirScore: 62,
    positive: 48,
    neutral: 30,
    negative: 22,
    articles: [
      { title: '삼성전자 주주모임 — 이번 분기 배당 예측', url: 'https://cafe.naver.com/samsung/1', sentiment: 'positive' },
      { title: '삼전 단기 매매 전략 공유합니다', url: 'https://cafe.naver.com/samsung/2', sentiment: 'neutral' },
      { title: '삼성전자 AS 최악 후기 공유', url: 'https://cafe.naver.com/samsung/complaint1', sentiment: 'negative' },
    ],
    flagged: [
      {
        title: '삼성전자 AS 최악 후기 공유',
        url: 'https://cafe.naver.com/samsung/complaint1',
        sentiment: 'negative',
        reason: 'CS 관련 부정 후기 다수 공감',
      },
    ],
  },
  {
    platformId: 'naver-blog',
    platformLabel: '네이버 블로그',
    category: 'SNS',
    sirScore: 76,
    positive: 68,
    neutral: 20,
    negative: 12,
    articles: [
      { title: '삼성전자 2026년 실적 분석 및 투자 포인트', url: 'https://blog.naver.com/samsung_analysis_1', sentiment: 'positive' },
      { title: '삼성전자 HBM 관련주 수혜 정리', url: 'https://blog.naver.com/samsung_analysis_2', sentiment: 'positive' },
      { title: '초보 투자자를 위한 삼성전자 기업 분석', url: 'https://blog.naver.com/samsung_analysis_3', sentiment: 'neutral' },
    ],
    flagged: [],
  },
];
